### ISSUE TITLE
 Class 'Webkul\Dropship\Providers\DropshipServiceProvider' not found

### ISSUE THREAD

**Issue by rashidshahzadali** [bagisto/laravel-aliexpress-dropship#44]
I am following all directions to integrate dropshipping but it showing me  Class 'Webkul\Dropship\Providers\DropshipServiceProvider' not found on the composer dump-autolaod I am wondering if this class is not available in the packages ? As i am uploaded all dropshipping packages to the root directory in packages

**Comment by prateek-webkul** [comment]
Hey @rashidshahzadali ,

You need to upload the dropship package under "packages/Webkul" directory, so it can load it from there. 

Thanks

**Comment by prateek-webkul** [comment]
Hey @rashidshahzadali ,

This issue has been opened for more than a month. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks

**Comment by mahbuburriad** [comment]
> Hey @rashidshahzadali ,
> 
> You need to upload the dropship package under "packages/Webkul" directory, so it can load it from there.
> 
> Thanks

Hello sir, I did upload to packages/Webkul but still same error. what to do? my PHP version 7.4 and bagisto version 1.3.1

**Comment by prateek-webkul** [comment]
Hey @mahbuburriad ,

We are working on compatibility with v1.3.1 and soon it's going to be released. Also, for issue run command **php artisan config:cache** .

Thanks

**Comment by sanjayacloud** [comment]
@rashidshahzadali , 
I have faced the same issue. Add following line instead of the "Webkul\\\\Dropship\\\\": "packages/Webkul/Dropship" in composer.json if you follow the step in "https://webkul.com/blog/laravel-aliexpress-dropshipping/". You will get this error. @prateek-webkul better if you can update the tutorial. 

""Webkul\\Dropship\\": "packages/Webkul/Dropship"
